name: CI - Dev

on:
    workflow_dispatch:
#    pull_request:
#         branches:
#             - main

jobs:
    setup:
        runs-on: ubuntu-latest
        name: File Alterations
        steps:
            -   name: Checkout the repository using git
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1
            