name: CI - Main

env:
    DELTA_HERBMAIL: false
    DELTA_KBVE: false
    DELTA_RAREICON: false
    DELTA_DISCORDSH: false
    DELTA_ATLAS: false

on:
    workflow_dispatch:
    push:
         branches:
             - main

concurrency:
    group: "pages"
    cancel-in-progress: true

# permissions:
#     actions: write
#     contents: write
#     pages: write
#     id-token: write

#   TODO: Matrix Setup 

jobs:
    alter:
        runs-on: ubuntu-latest
        name: File Alterations
        steps:
            -   name: Checkout the repository using git
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1
            
            -   name: File Changes
                id: delta
                uses: tj-actions/changed-files@v39
                with:
                  files_yaml: |
                    herbmail:
                        - 'apps/herbmail.com/**'
                    kbve: 
                        - 'apps/kbve.com/**'
                    rareicon:
                        - 'apps/rareicon.com/**'
                    discordsh:
                        - 'apps/discord.sh/**'
                    atlas:
                        - 'apps/atlas/kbve_atlas/**'

            -   name: Delta HerbMail
                if: steps.delta.outputs.herbmail_any_changed == 'true'  
                run: |
                    echo "One or more HerbMail file(s) has changed."
                    echo "List all the files that have changed: ${{ steps.delta.outputs.herbmail_all_changed_files }}"
                    echo "DELTA_HERBMAIL=true" >> $GITHUB_ENV
            
            -   name: Delta KBVE
                if: steps.delta.outputs.kbve_any_changed == 'true'  
                run: |
                        echo "One or more KBVE file(s) has changed."
                        echo "List all the files that have changed: ${{ steps.delta.outputs.kbve_all_changed_files }}"
                        echo "DELTA_KBVE=true" >> $GITHUB_ENV

            -   name: Delta RareIcon
                if: steps.delta.outputs.rareicon_any_changed == 'true'
                run: |
                        echo "Changes in RareIcon file(s) has changed."
                        echo "List all the files that have changed: ${{ steps.delta.outputs.rareicon_all_changed_files }}"
                        echo "DELTA_RAREICON=true" >> $GITHUB_ENV
            
            -   name: Delta Discordsh
                if: steps.delta.outputs.discordsh_any_changed == 'true'
                run: |
                        echo "Changes in DiscordSh file(s) has changed."
                        echo "List all the files that have changed: ${{ steps.delta.outputs.discordsh_all_changed_files }}"
                        echo "DELTA_DISCORDSH=true" >> $GITHUB_ENV
            
            -   name: Delta Atlas
                if: steps.delta.outputs.atlas_any_changed == 'true'
                run: |
                        echo "Changes in Atlas file(s) has changed."
                        echo "List all the files that have changed: ${{ steps.delta.outputs.atlas_all_changed_files }}"
                        echo "DELTA_ATLAS=true" >> $GITHUB_ENV

    deploy:
        needs: alter
        name: Deployment
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the repository using git
                uses: actions/checkout@v4
            
            -   name: Setup Node
                uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Setting up pnpm
                uses: pnpm/action-setup@v2
                with:
                    version: 8

            -   name: Install dependencies
                run: pnpm install

            -   name: Deployment Test Case
                shell: bash
                run: |
                    pnpm nx report

            -   name: Python Install
                if: needs.alter.outputs.atlas_any_changed == 'true'
                uses: actions/setup-python@v4
                with:
                  python-version: "3.x"
            
            -   name: Poetry Install
                if: needs.alter.outputs.atlas_any_changed == 'true'
                uses: snok/install-poetry@v1

            -   name: Atlas Deployment
                if: needs.alter.outputs.atlas_any_changed == 'true'
                shell: bash
                run: |
                    pnpm nx build atlas
            
            -   name: Store the distribution packages
                if: needs.alter.outputs.atlas_any_changed == 'true'
                uses: actions/upload-artifact@v3
                with:
                    name: atlas-python-package-distributions
                    path: apps/atlas/dist/
    
    pypublish:
        needs: ["deploy", "alter"]
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/kbve
        permissions:
            id-token: write 
        steps:
            -   name: Download all the dists
                if: needs.alter.outputs.atlas_any_changed == 'true'
                uses: actions/download-artifact@v3
                with:
                    name: atlas-python-package-distributions
                    path: apps/atlas/dist/
            -   name: Publish distribution 📦 to PyPI
                if: needs.alter.outputs.atlas_any_changed == 'true'
                uses: pypa/gh-action-pypi-publish@release/v1
            