name: CI - Main

env:
    DELTA_HERBMAIL: false
    DELTA_KBVE: false
    DELTA_RAREICON: false
    DELTA_DISCORDSH: false
    DELTA_ATLAS: false

on:
    workflow_dispatch:
    push:
         branches:
             - main

concurrency:
    group: "pages"
    cancel-in-progress: true

# permissions:
#     actions: write
#     contents: write
#     pages: write
#     id-token: write

#   TODO: Matrix Setup 

jobs:
    alter:
        runs-on: ubuntu-latest
        name: File Alterations
        steps:
            -   name: Checkout the repository using git
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1
            
            -   name: File Changes
                id: delta
                uses: tj-actions/changed-files@v39
                with:
                  files_yaml: |
                    herbmail:
                        - 'apps/herbmail.com/**'
                    kbve: 
                        - 'apps/kbve.com/**'
                    rareicon:
                        - 'apps/rareicon.com/**'
                    discordsh:
                        - 'apps/discord.sh/**'
                    atlas:
                        - 'apps/atlas/kbve_atlas/**'

            -   name: Delta HerbMail
                if: steps.delta.outputs.herbmail_any_changed == 'true'  
                run: |
                    echo "One or more HerbMail file(s) has changed."
                    echo "List all the files that have changed: ${{ steps.delta.outputs.herbmail_all_changed_files }}"
            
            -   name: Delta KBVE
                if: steps.delta.outputs.kbve_any_changed == 'true'  
                run: |
                        echo "One or more KBVE file(s) has changed."
                        echo "List all the files that have changed: ${{ steps.delta.outputs.kbve_all_changed_files }}"
                
            -   name: Delta RareIcon
                if: steps.delta.outputs.rareicon_any_changed == 'true'
                run: |
                        echo "Changes in RareIcon file(s) has changed."
                        echo "List all the files that have changed: ${{ steps.delta.outputs.rareicon_all_changed_files }}"
            
            -   name: Delta Discordsh
                if: steps.delta.outputs.discordsh_any_changed == 'true'
                run: |
                        echo "Changes in DiscordSh file(s) has changed."
                        echo "List all the files that have changed: ${{ steps.delta.outputs.discordsh_all_changed_files }}"
            
            -   name: Delta Atlas
                if: steps.delta.outputs.atlas_any_changed == 'true'
                run: |
                        echo "Changes in Atlas file(s) has changed."
                        echo "List all the files that have changed: ${{ steps.delta.outputs.discordsh_all_changed_files }}"

    deploy:
        needs: alter
        name: Deployment
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the repository using git
                uses: actions/checkout@v4
            
            -   name: Setup Node
                uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: Setting up pnpm
                uses: pnpm/action-setup@v2
                with:
                    version: 8
                    run_install: |
                        - args: [--global, nx@latest]

            -   name: Deployment Test Case
                shell: bash
                run: |
                    nx report