name: CI

on:
    pull_request:
        branches:
            - main

# permissions:
#     actions: write
#     contents: write
#     pages: write
#     id-token: write

jobs:
    alter:
        runs-on: ubuntu-latest
        name: File Alterations
        steps:
            -   name: Checkout the repository using git
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1
            
            -   name: HerbMail Changes
                id: changed-files-yaml
                uses: tj-actions/changed-files@v39
                with:
                  files_yaml: |
                    herbmail:
                      - 'apps/herbmail.com/**'
            
            -   name: Check HerbMailfor Changes
                if: steps.changed-files-yaml.outputs.herbmail_any_changed == 'true'  
                run: |
                    echo "One or more test file(s) has changed."
                    echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.herbmail_all_changed_files }}"
                