name: Organize Labels

on:
    issues:
        types: [labeled]

jobs:
    assign_concepts:
        name: "Enhancement Label Automation"
        if: github.event.label.name == 'enhancement'
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/gql-project-migration
                with:
                    token: ${{ secrets.KBVE_PAT }}
                    key: "Status"
                    value: "Theory"
                    idref: ${{ github.event.issue.node_id }}

    assign_bug:
        name: "Bug Label Automation"
        if: github.event.label.name == 'bug'
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: ./.github/actions/gql-project-migration
                with:
                    token: ${{ secrets.KBVE_PAT }}
                    key: "Status"
                    value: "Error"
                    idref: ${{ github.event.issue.node_id }}

    